sudo: required
services: docker
language: elixir
elixir:
  - 1.3

before_install:
  - docker pull neo4j:3.0.6
  - docker run -d -p 127.0.0.1:7687:7687 -e 'NEO4J_AUTH=neo4j/password' neo4j:3.0.6
  - |
    cat <<-EOF > /tmp/wait-for-neo4j.sh
    while [ ! nc -z -v 127.0.0.1 7687 ]; do echo "Waiting for neo4j" && sleep 5; done
    EOF
  - bash /tmp/wait-for-neo4j.sh


script:
  - mix test --include neo4j
