sudo: required
services: docker
language: elixir
elixir:
  - 1.3

before_install:
  - docker run --name neo4j -d -p 127.0.0.1:7687:7687 -e 'NEO4J_AUTH=neo4j/password' neo4j:3.0.6
  - docker logs -f neo4j | sed '/Remote interface available/q'

script:
  - mix test --include neo4j
