sudo: required
services: docker
language: elixir
elixir:
  - 1.3

before_install:
  - docker pull neo4j:3.0.6
  - docker run -d -p 7687:7687 -e 'NEO4J_AUTH=neo4j/password' neo4j:3.0.6
  - docker ps -a

script:
  - mix test --include neo4j
